on: [push, pull_request]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-11, windows-2019, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install clang-tidy on ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install -y clang-tidy

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
